include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
    require_trailing_commas: error

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    avoid_annotating_with_dynamic: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false
