name: nuforce
version: 1.0.0+6
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  get: 4.6.5
  image_picker: ^1.0.4
  intl_phone_number_input: ^0.7.3+1
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^3.0.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_sliders: ^23.1.40
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.0.7
  textfield_tags: ^2.0.2
  carousel_slider: ^4.2.1
  pie_chart: ^5.4.0
  equatable: ^2.0.5
  flutter_colorpicker: ^1.0.3


dev_dependencies:
  build_runner: 2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: 2.0.2
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
