name: nuforce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.5
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.0.7
  flutter_native_splash: ^2.3.2
  percent_indicator: ^4.2.3
  pinput: ^3.0.0
  intl_phone_number_input: ^0.7.3+1
  persistent_bottom_nav_bar: ^5.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.2
  build_runner: 2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
