name: nuforce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.5
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
