name: nuforce
version: 1.0.0+6
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_material_color_picker: ^1.2.0
  flutter_native_splash: ^2.3.2
  flutter_quill: ^9.3.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.4
  get: 4.6.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  logger: ^2.0.2+1
  multi_select_flutter: ^4.1.3
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  pie_chart: ^5.4.0
  pinput: ^3.0.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_sliders: ^23.1.40
  textfield_tags: ^2.0.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.11
  uuid: ^4.3.3
  webview_flutter: ^4.0.7
  custom_date_range_picker: ^1.0.10
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.7.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^23.2.7
  easy_stepper: ^0.8.3
  flutter_widget_from_html: ^0.15.0
dev_dependencies:
  build_runner: 2.4.6
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
  # very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
